version: '3.9'

services:
  data-simulator:
    build:
      context: data-simulator
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    environment:
      - IOT_CONTROLLER_URL=http://iot-controller:9090
    depends_on:
      - iot-controller

  iot-controller:
    build:
      context: controller
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_MONGODB_HOST=mongo-controller
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - mongo-controller
      - rabbitmq

  mongo-controller:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-controller-data:/data/db

  mongo-rule-engine:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-rule-engine-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo-controller

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  mongo-controller-data:
    driver: local
  mongo-rule-engine-data:
    driver: local
