#filebeat.inputs:
#  - type: log
#    enabled: true
#    paths:
#      - /rule_engine_app/rule_engine_app.log
#    # В fields мы можем указать дополнительные поля, а затем в logstash вытаскивать их
#    # и делать какую-нибудь дополнительную работу с логами
#    fields:
#      # Название нашего сервиса
#      service: rule_engine_app
#
#output.logstash:
#  # Будьте внимательны при запуске вне докера и вместо logstash укажите правильный адрес хоста с logstash.
#  hosts: ["logstash:5044"]
