server:
  port: ${RULE_ENGINE_SERVICE_PORT:8080}

spring:
  application:
    name: rule-engine

  data:
    mongodb:
      host: ${SPRING_MONGODB_HOST:localhost}
      port: ${SPRING_MONGODB_PORT:27018}
      database: ${SPRING_MONGODB_DATABASE:admin}
      username: ${SPRING_MONGODB_USERNAME:admin}
      password: ${SPRING_MONGODB_PASSWORD:admin}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}
    queue: ${SPRING_RABBITMQ_QUEUE_NAME:devicePackages}
    listener:
      simple:
        auto-startup: true
        concurrency: 1
        max-concurrency: 4
        default-requeue-rejected: false
  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always

logging:
  level:
    org.springframework.boot.actuate: DEBUG
